spring.datasource.url=jdbc:mysql://localhost:3306/cinema_management?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
server.port=8080

logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.com.example.cinema_management=DEBUG

# Use migrations to create tables
spring.flyway.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=susangicharuni@gmail.com
spring.mail.password=nbiqrkjdcveagtmu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true