spring.application.name=Smart Cinema Ticketing System
spring.jpa.hibernate.ddl-auto=validate

# TMDB
tmdb.image-base-url=https://image.tmdb.org/t/p/
tmdb.image-size=w500
tmdb.default-language=en-US
tmdb.default-region=US
tmdb.download-posters=true
tmdb.api-key=ae93b38d46a6d892bc4f96f097564b74

# Local media

app.media.posters-url-base=/uploads/posters
app.media.posters-dir=uploads/posters

# Buffer (in minutes) between sessions on the same screen.
# Set to 0 to allow back-to-back shows that exactly touch.
schedules.bufferMinutes=15